### ISSUE TITLE
Image update : security concern ?

### ISSUE THREAD

**Issue by shad-lp** [sjawhar/docker-socket-proxy#1]
Hi @sjawhar 

Thanks for this image, I'm using it for some years now without any problem.
I was just wondering if I should still use it since there has been no update for 4 years now.
Any security concern I should be aware of ?

Thanks again.

**Comment by sjawhar** [comment]
Hey there! It's a very simple image, so the only concern would be if there's a vulnerability in one of alpine and socat (which I'm not sure of, because I'm honestly not keeping track). Nonetheless, I've updated to the latest version of each and pushed a new image. Thanks!
